name: skills
stack:
  - markdown
  - bash
  - git
  - github-cli
runtime:
  default: bun
  notes: Bun-first environment; scripts are shell-based.
conventions:
  harness: AGENTS.md
  worktree:
    root_priority:
      - .worktrees
      - worktrees
      - ~/.config/opencode/worktrees/{project}
    default_base: current-branch
    require_gitignore: true
  pr:
    default_base: main
    merge_method: squash
scripts:
  preflight: .agents/skills/worktree-feature-execution/scripts/preflight-check.sh
  create_worktree: .agents/skills/worktree-feature-execution/scripts/create-worktree.sh
  sync_worktree: .agents/skills/worktree-feature-execution/scripts/sync-worktree.sh
  open_pr: .agents/skills/worktree-feature-execution/scripts/open-pr.sh
  merge_pr: .agents/skills/worktree-feature-execution/scripts/merge-pr.sh
  cleanup_worktree: .agents/skills/worktree-feature-execution/scripts/cleanup-worktree.sh
